name: Itch Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release, for example 1.2.3"
        required: true
        type: string

env:
  GODOT_VERSION: 4.7
  ADDON_DIR: rpg_dialogue
  ADDON_EXPORT_NAME: rpgdl
  BUILD_VERSION: ${{ inputs.version || github.ref_name }}

jobs:

  export-addon:
    name: Zip Addon
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update plugin version
        shell: bash
        run: |
          PLUGIN_FILE="addons/${{ env.ADDON_DIR }}/plugin.cfg"
          sed -i -E \
            's/^version="[^"]*"/version="${{ env.BUILD_VERSION }}"/' \
            "$PLUGIN_FILE"
          grep '^version=' "$PLUGIN_FILE"

      - name: Create ZIP structure
        run: |
          mkdir -p package/addons/${{ env.ADDON_DIR }}
          cp -R addons/${{ env.ADDON_DIR }}/. package/addons/${{ env.ADDON_DIR }}/
  # Addition files:
  #       cp USE_AND_ATTRIBUTION.txt package/USE_AND_ATTRIBUTION.txt

      - name: Create addon ZIP
        run: |
          cd package
          zip -r ../${{ env.ADDON_EXPORT_NAME }}.zip .
      
      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ADDON_EXPORT_NAME }}
          path: ${{ env.ADDON_EXPORT_NAME }}.zip
          if-no-files-found: error

  deploy-addon:
    needs: export-addon
    name: Upload Addon Zip to Itch
    runs-on: ubuntu-latest
    steps:
      - name: Download ZIP artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ADDON_EXPORT_NAME }}
          path: ./build

      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.ITCH_BUTLER_API_KEY }}
          gameData: ./build/${{ env.ADDON_EXPORT_NAME }}.zip
          itchUsername: ${{ vars.ITCH_USERNAME }}
          itchGameId: ${{ vars.ITCH_GAME_ID }}
          buildChannel: godot4-addon # gets appended to the filename
          buildNumber: ${{ env.BUILD_VERSION }}



  # export-web:
  #   runs-on: ubuntu-24.04 # Use 24.04 with godot 4
  #   container:
  #     image: barichello/godot-ci:4.7.2
  #     # https://hub.docker.com/r/barichello/godot-ci/tags
  #   steps: 
  #   - name: Checkout
  #     uses: actions/checkout@v4
  #     with:
  #       lfs: true
  #   - name: Setup
  #     run: |
  #       mkdir -v -p ~/.local/share/godot/export_templates/
  #       mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
  #   - name: Web Build
  #     run: |
  #       mkdir -v -p build/web
  #       EXPORT_DIR="$(readlink -f build)"
  #       godot --headless --verbose --export-release "ItchioHtml5" "$EXPORT_DIR/web/index.html"
  #   - name: Upload Artifact
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: web
  #       path: build/web
  #       retention-days: 7
  # deploy:
  #   needs: export-web
  #   name: Upload to Itch
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: web
  #         path: build/web
  #     - uses: KikimoraGames/itch-publish@v0.0.3
  #       with:
  #         butlerApiKey: ${{ secrets.ITCH_BUTLER_API_KEY }}
  #         gameData: ./build/
  #         itchUsername: ${{ vars.ITCH_USERNAME }}
  #         itchGameId: ${{ vars.ITCH_GAME_ID }}
  #         buildChannel: html